### ISSUE TITLE
Action "sold"

### ISSUE THREAD

**Issue by domagojmedo** [C1rdec/PoeLurker#1]
Can you add quick reply that sends "sold" to buyer like Mercury trade?

**Comment by C1rdec** [comment]
Yeah I will but I just dont know how to implement the UI yet any idea?

**Comment by domagojmedo** [comment]
Instead of clickable corners you can have multiple rows over the whole square shown on hover. You could fit more actions there.
Or have the square expand on hover. (it should expand up instaed of left or right if you go this route to not mess up position of other squares)

Mercury trade has really good UI for trades in my opinion I just dislike the rest of it and would preffer to use your .NET solution

**Comment by EirikAskheim** [comment]
How about using modify keys for more than 3 actions? Ctrl and/or alt. Then you can keep the UI small and have up to 12 actions (none / c / a / c+a) * 3.

**Comment by Blekota2k** [comment]
How about some rollout bar with custom buttons for what ever message/action user wants (sold and close, no ty and close, 1 min and party inv etc)

**Comment by C1rdec** [comment]
I love you guys <3

**Comment by C1rdec** [comment]
> How about using modify keys for more than 3 actions? Ctrl and/or alt. Then you can keep the UI small and have up to 12 actions (none / c / a / c+a) * 3.
> 
> Edit: + Shift

I like the idea alot

**Comment by C1rdec** [comment]
What about this?
![image](https://user-images.githubusercontent.com/5436436/71699016-ae86df00-2d8b-11ea-877e-c035e40777f7.png)

**Comment by Blekota2k** [comment]
> @Blekota2k
> Vertical rollout ?
> ![image](https://user-images.githubusercontent.com/5436436/71684414-6f449800-2d63-11ea-9433-49cf34dc5212.png)
> 
> Ps: I love you guys <3

it rly doesnt matter where or how the rollout will work since it dosnt need to be compact anymore. you want small ikon, like it is now, when you r maping or boss fighting and dont want whole screen filled with trading ikons, but when you want to trade, you hover over the ikon and some variable list of actions cen pop up. and yes, for example as you showed on the image :)

**Comment by C1rdec** [comment]
This feature is in the Release 1.0.2 (CTRL + Click) on the Main action
