### ISSUE TITLE
Empty Task switcher entry (Win 10)

### ISSUE THREAD

**Issue by ghr74** [C1rdec/PoeLurker#11]
On Windows 10, when using the task switcher (Alt+Tab), PoeLurker has a large, empty entry (see screenshot)
![2020-01-05_06-00-16](https://user-images.githubusercontent.com/28192634/71775428-426dcc00-2f81-11ea-8a01-eb9dff6c7050.png)
.
Would probably be best to just hide it.

**Comment by C1rdec** [comment]
On it

**Comment by C1rdec** [comment]
Fixed with [https://github.com/C1rdec/PoeLurker/releases/tag/v1.1.1](v1.1.1)
