### ISSUE TITLE
Question, more than issue, about sub actions

### ISSUE THREAD

**Issue by Maldini999** [C1rdec/PoeLurker#13]
The two main actions (invite and request trade) work for me.

The two initial sub actions of Deny and Busy also work for me.

I can see in the latest release you added message support for Thank You and Sold sub actions.

But I don't see those new sub functions show up on the icon.  Is there something I need to do to get the new sub actions to appear on the icon like the Deny and Busy sub actions already do?

thank you!

**Comment by C1rdec** [comment]
SOLD can be perform while holding CTRL + Click on main action.
And to send a Thank you message you need to set a message in the PoeLurker.exe.config

![image](https://user-images.githubusercontent.com/5436436/71787555-767bd800-2fe7-11ea-9d3a-6b8ed3fa34b3.png)

**Comment by Maldini999** [comment]
thank you!

I had previously edited the cfg file to add my thank you message, but I did not know to use Cntl to access the new sub functions.

**Comment by C1rdec** [comment]
Yeah I'll make a wiki 😂😅

**Comment by Maldini999** [comment]
The Sold works perfectly, just as you suggested but I still don't understand how to use the thank you sub action.

After my trade is complete, the poelurker icon disappears but that is when I want to say thank you.  

Is there a way the icon can remain, allow me to click a button to say thank you and then that action closes the icon?

**Comment by Maldini999** [comment]
never mind.  I get it now :)  It sends the Thank you message automatically.

Excellent :)

**Comment by C1rdec** [comment]
💋
