### ISSUE TITLE
Suggestion - same area display

### ISSUE THREAD

**Issue by briandinh1** [C1rdec/PoeLurker#14]
Instead of having a small icon in the box when a person enters the same area, how about lighting up the border instead? For example, give it a gold border kind of like how the map tab has the bar for completion. It is a lot more easily recognizable at a quick glance. I find the little person icon hard to see sometimes. 

![8o8tjqd0cn841](https://user-images.githubusercontent.com/5378877/71788922-a1b4f600-2fec-11ea-81b4-c22c5898dd27.png)

**Comment by C1rdec** [comment]
The border will be the active trade (The one that displays the item name)

**Comment by C1rdec** [comment]
But I'm up for new idea regarding Hideout

**Comment by briandinh1** [comment]
maybe just a big exclamation point over the currency icon? lol. or just a brighter colored version of the same icon we already have now.

**Comment by C1rdec** [comment]
How's that?
![image](https://user-images.githubusercontent.com/5436436/71792885-74764100-3008-11ea-83dd-8795adf21009.png)

**Comment by briandinh1** [comment]
that looks great!

**Comment by C1rdec** [comment]
You can download [v1.1.2](https://github.com/C1rdec/PoeLurker/releases/tag/v1.1.2) ;)
