### ISSUE TITLE
Can't get it to work, nothing happends when It get whispers

### ISSUE THREAD

**Issue by Pjey900** [C1rdec/PoeLurker#3]
Could it be becuase I got a newer version of Framework? I don't feel like installing the older version since other programs might bug out then too

**Comment by C1rdec** [comment]
Are you running the game in Fullscreen or are you on Windows 7

**Comment by Pjey900** [comment]
> Are you running the game in Fullscreen or are you on Windows 7
I'm running the game on fullscreen windowed, windows 10

**Comment by Deop** [comment]
I'm running windowed fullscrean, windows 10. Sometimes having issues with not sending out invites/trades. Possible cause is that I have chat active (hit Enter).
Might be related to OP issue, or separate.

**Comment by C1rdec** [comment]
@Pjey900 Can we connect on Discord?

**Comment by zulrang** [comment]
I'm having the same issue.  It's running, the game is running Fullscreen Windowed, and nothing is happening.  Shoot me a discord link because I'd also like to contribute.

**Comment by C1rdec** [comment]
https://discord.gg/eX48y5

**Comment by C1rdec** [comment]
Seems to be related to 4k resolution

**Comment by zymox** [comment]
Doesn't work for me either - I'm playing Windowed Fullscreen with 2560x1440 resolution.
The PoeLurker windows seems to be there, but I can't see it, unless I ALT+TAB: https://imgur.com/a/UavMmWX

**Comment by boyvanduuren** [comment]
> Are you running the game in Fullscreen or **are you on Windows 7**

Is windows 7 supported?

**Comment by C1rdec** [comment]
#9 Lets compile all the information on this issue
The issue seem to happen to user havibg karge screen resolution
