### ISSUE TITLE
[Feature Request] Thank you message

### ISSUE THREAD

**Issue by Ragura** [C1rdec/PoeLurker#5]
Would it be possible to integrate a third state to the main button? First is invite, second is trade, third is thank you message? Would make sense in sequence, right?

Thanks for working on this, it's a nice minimalistic way of handling the interactions!

**Comment by C1rdec** [comment]
It wont because the trade offer closed after the trade is succeeded... I'll make message customization so when the trade is succeeded and you did setup a "Thank you" message the whisper will go out.
